"""
Django settings for cap project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from .settings import *
load_dotenv()
HOSTNAME = os.getenv("HOSTNAME")
PORT_FRONTEND = os.getenv("PORT_FRONTEND")
DOMAIN = os.getenv("DOMAIN")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [HOSTNAME,DOMAIN,'localhost']



CORS_ALLOWED_ORIGINS = [
#    'http://*',
#    'https://*',
    f'http://{HOSTNAME}:{PORT_FRONTEND}',
    f'http://{HOSTNAME}:3000',
    f'http://{HOSTNAME}:3001',
    f'http://{DOMAIN}:3000',
    f'http://{DOMAIN}:3001',
    f'http://{HOSTNAME}',
    f'https://{DOMAIN}',
    f'http://localhost',
    f'http://localhost:3000',
    f'http://localhost:3001',
]


DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE"),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"), 

    }
}

REST_REGISTRATION = {
    'REGISTER_VERIFICATION_URL': f'http://{HOSTNAME}:{PORT_FRONTEND}/verify-user/',
    'RESET_PASSWORD_VERIFICATION_URL': f'http://{HOSTNAME}:{PORT_FRONTEND}/reset-password/',
    'REGISTER_EMAIL_VERIFICATION_URL': f'http://{HOSTNAME}:{PORT_FRONTEND}/verify-email/',
    'LOGIN_RETRIEVE_TOKEN': True,
    'VERIFICATION_FROM_EMAIL': 'no-reply@csariel.xyz',
    'REGISTER_VERIFICATION_EMAIL_TEMPLATES': {
        'subject':  'verify_email/email_verification_subject.txt',
        'html_body':  'verify_email/email_verification_msg.html'
    },
       'RESET_PASSWORD_VERIFICATION_EMAIL_TEMPLATES': {
        'subject':  'reset_password/user_reset_password.txt',
        'html_body':  'reset_password/user_reset_password.html'
    },
    'REGISTER_SERIALIZER_CLASS': 'api.serializers.RegisterUserSerializer',

}

NOSE_ARGS = ['--nocapture',
             '--nologcapture',]


# email varification settings
LOGIN_URL = f'http://{HOSTNAME}:{PORT_FRONTEND}/'
