version: '3.7'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=postgres
      - PG_PORT=5432

  db:
    image: postgres:16
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
