# Generated by Django 3.1.6 on 2023-08-02 06:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=32, unique=True)),
                ('Semester', models.CharField(choices=[('א', 'א'), ('ב', 'ב'), ('ק', 'ק')], max_length=5, null=True)),
                ('lecturer', models.CharField(max_length=32)),
                ('capacity', models.IntegerField()),
                ('day', models.CharField(choices=[('א', 'א'), ('ב', 'ב'), ('ג', 'ג'), ('ד', 'ד'), ('ה', 'ה'), ('ו', 'ו')], max_length=5, null=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='תעודת הזהות חייבת להיות 9 ספרות', regex='^.{9}$')])),
                ('amount_elective', models.IntegerField(null=True)),
                ('program', models.CharField(blank=True, choices=[('1', 'BASIC'), ('2', 'EXCELLENCE')], default='1', max_length=2, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='api.Course')),
                ('office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('is_elective', models.BooleanField(default=True)),
                ('groups', models.IntegerField(null=True)),
                ('office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.office')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.course_group'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
                'index_together': {('course', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
                'index_together': {('course', 'student')},
            },
        ),
    ]
