# Generated by Django 3.1.6 on 2023-08-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ranking_is_included'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='is_included',
            new_name='is_acceptable',
        ),
    ]
