# Generated by Django 3.1.6 on 2023-09-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ranking_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Result_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_txt', models.TextField()),
                ('explanation', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
