# Generated by Django 3.1.6 on 2023-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230807_1400'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course_group',
            constraint=models.UniqueConstraint(fields=('name', 'office'), name='office_course'),
        ),
    ]
