# Generated by Django 3.1.6 on 2023-08-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230808_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_group',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
