# Generated by Django 3.1.6 on 2023-09-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230906_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_info',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
